/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Custom__factory } from "./ERC20Custom__factory";
export { Erc20TokenFactory__factory } from "./Erc20TokenFactory__factory";
export { IERC20__factory } from "./IERC20__factory";
